server:
  server_name: user_info_server
  port: 50051
  log: ./access.log
mysql:
  master:
    ip: '127.0.0.1'
    port: 3306
    user: root
    passwd: lsh@1030@
  slave:
    ip: '127.0.0.1'
    port: 3306
    user: root
    passwd: lsh@1030@